[package]
name = "protos"
version = "0.1.0"
authors = ["Eadral <a250014238@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
grpcio = "0.4"
protobuf = "2"
futures = "0.1"