[package]
name = "compute"
version = "0.1.0"
authors = ["zyc"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
protos = { path = "../protos"}
grpcio = "0.4"
futures = "0.1"